/** Service names (matches hmi_api TABLE_SERVICES) */
export const TABLE_SERVICES = [
  'line_mst',
  'equip_mst',
  'sensor_mst',
  'worker_mst',
  'shift_cfg',
  'kpi_cfg',
  'alarm_cfg',
  'maint_cfg',
  'work_order',
  'parts_mst',
  'defect_code_mst',
  'measurement',
  'status_his',
  'prod_his',
  'defect_his',
  'alarm_his',
  'maint_his',
  'shift_map',
  'kpi_sum',
] as const

/** Per-table API operations (matches actual router endpoints) */
export const SERVICE_OPERATIONS: Record<string, Array<{ method: 'GET' | 'POST' | 'PATCH' | 'DELETE'; path: string; label: string }>> = {
  line_mst: [
    { method: 'GET', path: '/line_mst', label: 'List' },
    { method: 'POST', path: '/line_mst', label: 'Create' },
    { method: 'GET', path: '/line_mst/{id}', label: 'Get' },
    { method: 'PATCH', path: '/line_mst/{id}', label: 'Update' },
    { method: 'DELETE', path: '/line_mst/{id}', label: 'Delete' },
  ],
  equip_mst: [
    { method: 'GET', path: '/equip_mst', label: 'List' },
    { method: 'POST', path: '/equip_mst', label: 'Create' },
    { method: 'GET', path: '/equip_mst/{id}', label: 'Get' },
    { method: 'PATCH', path: '/equip_mst/{id}', label: 'Update' },
    { method: 'DELETE', path: '/equip_mst/{id}', label: 'Delete' },
  ],
  sensor_mst: [
    { method: 'GET', path: '/sensor_mst', label: 'List' },
    { method: 'POST', path: '/sensor_mst', label: 'Create' },
    { method: 'GET', path: '/sensor_mst/{id}', label: 'Get' },
    { method: 'PATCH', path: '/sensor_mst/{id}', label: 'Update' },
    { method: 'DELETE', path: '/sensor_mst/{id}', label: 'Delete' },
  ],
  worker_mst: [
    { method: 'GET', path: '/worker_mst', label: 'List' },
    { method: 'POST', path: '/worker_mst', label: 'Create' },
    { method: 'GET', path: '/worker_mst/{id}', label: 'Get' },
    { method: 'PATCH', path: '/worker_mst/{id}', label: 'Update' },
    { method: 'DELETE', path: '/worker_mst/{id}', label: 'Delete' },
  ],
  shift_cfg: [
    { method: 'GET', path: '/shift_cfg', label: 'List' },
    { method: 'POST', path: '/shift_cfg', label: 'Create' },
    { method: 'GET', path: '/shift_cfg/{id}', label: 'Get' },
    { method: 'PATCH', path: '/shift_cfg/{id}', label: 'Update' },
    { method: 'DELETE', path: '/shift_cfg/{id}', label: 'Delete' },
  ],
  kpi_cfg: [
    { method: 'GET', path: '/kpi_cfg', label: 'List' },
    { method: 'POST', path: '/kpi_cfg', label: 'Create' },
    { method: 'GET', path: '/kpi_cfg/{id}', label: 'Get' },
    { method: 'PATCH', path: '/kpi_cfg/{id}', label: 'Update' },
    { method: 'DELETE', path: '/kpi_cfg/{id}', label: 'Delete' },
  ],
  alarm_cfg: [
    { method: 'GET', path: '/alarm_cfg', label: 'List' },
    { method: 'POST', path: '/alarm_cfg', label: 'Create' },
    { method: 'GET', path: '/alarm_cfg/{id}', label: 'Get' },
    { method: 'PATCH', path: '/alarm_cfg/{id}', label: 'Update' },
    { method: 'DELETE', path: '/alarm_cfg/{id}', label: 'Delete' },
  ],
  maint_cfg: [
    { method: 'GET', path: '/maint_cfg', label: 'List' },
    { method: 'POST', path: '/maint_cfg', label: 'Create' },
    { method: 'GET', path: '/maint_cfg/{id}', label: 'Get' },
    { method: 'PATCH', path: '/maint_cfg/{id}', label: 'Update' },
    { method: 'DELETE', path: '/maint_cfg/{id}', label: 'Delete' },
  ],
  work_order: [
    { method: 'GET', path: '/work_order', label: 'List' },
    { method: 'POST', path: '/work_order', label: 'Create' },
    { method: 'GET', path: '/work_order/{id}', label: 'Get' },
    { method: 'PATCH', path: '/work_order/{id}', label: 'Update' },
    { method: 'DELETE', path: '/work_order/{id}', label: 'Delete' },
  ],
  parts_mst: [
    { method: 'GET', path: '/parts_mst', label: 'List' },
    { method: 'POST', path: '/parts_mst', label: 'Create' },
    { method: 'GET', path: '/parts_mst/{id}', label: 'Get' },
    { method: 'PATCH', path: '/parts_mst/{id}', label: 'Update' },
    { method: 'DELETE', path: '/parts_mst/{id}', label: 'Delete' },
  ],
  defect_code_mst: [
    { method: 'GET', path: '/defect_code_mst', label: 'List' },
    { method: 'POST', path: '/defect_code_mst', label: 'Create' },
    { method: 'GET', path: '/defect_code_mst/{id}', label: 'Get' },
    { method: 'PATCH', path: '/defect_code_mst/{id}', label: 'Update' },
    { method: 'DELETE', path: '/defect_code_mst/{id}', label: 'Delete' },
  ],
  measurement: [
    { method: 'GET', path: '/measurement', label: 'List' },
  ],
  status_his: [
    { method: 'GET', path: '/status_his', label: 'List' },
    { method: 'GET', path: '/status_his/{id}', label: 'Get' },
  ],
  prod_his: [
    { method: 'GET', path: '/prod_his', label: 'List' },
    { method: 'GET', path: '/prod_his/{id}', label: 'Get' },
  ],
  defect_his: [
    { method: 'GET', path: '/defect_his', label: 'List' },
    { method: 'GET', path: '/defect_his/{id}', label: 'Get' },
    { method: 'POST', path: '/defect_his', label: 'Create' },
  ],
  alarm_his: [
    { method: 'GET', path: '/alarm_his', label: 'List' },
    { method: 'GET', path: '/alarm_his/{id}', label: 'Get' },
  ],
  maint_his: [
    { method: 'GET', path: '/maint_his', label: 'List' },
    { method: 'GET', path: '/maint_his/{id}', label: 'Get' },
  ],
  shift_map: [
    { method: 'GET', path: '/shift_map', label: 'List' },
    { method: 'POST', path: '/shift_map', label: 'Create' },
    { method: 'GET', path: '/shift_map/{id}', label: 'Get' },
    { method: 'PATCH', path: '/shift_map/{id}', label: 'Update' },
    { method: 'DELETE', path: '/shift_map/{id}', label: 'Delete' },
  ],
  kpi_sum: [
    { method: 'GET', path: '/kpi_sum', label: 'List' },
    { method: 'GET', path: '/kpi_sum/{id}', label: 'Get' },
  ],
}

/** Service titles and descriptions for card display */
export const SERVICE_INFO: Record<string, { title: string; description: string }> = {
  line_mst: { title: 'Line Master', description: '라인 마스터 정보 관리 API 서비스' },
  equip_mst: { title: 'Equipment Master', description: '설비 마스터 정보 관리 API 서비스' },
  sensor_mst: { title: 'Sensor Master', description: '센서 마스터 정보 관리 API 서비스' },
  worker_mst: { title: 'Worker Master', description: '작업자 마스터 정보 관리 API 서비스' },
  shift_cfg: { title: 'Shift Config', description: '근무 교대 설정 관리 API 서비스' },
  kpi_cfg: { title: 'KPI Config', description: 'KPI 설정 관리 API 서비스' },
  alarm_cfg: { title: 'Alarm Config', description: '알람 설정 관리 API 서비스' },
  maint_cfg: { title: 'Maintenance Config', description: '보전 설정 관리 API 서비스' },
  work_order: { title: 'Work Order', description: '작업 지시 정보 관리 API 서비스' },
  parts_mst: { title: 'Parts Master', description: '부품 마스터 정보 관리 API 서비스' },
  defect_code_mst: { title: 'Defect Code', description: '불량 코드 마스터 API 서비스' },
  measurement: { title: 'Measurement', description: '측정 데이터 수집 및 조회 API 서비스' },
  status_his: { title: 'Status History', description: '설비 상태 이력 조회 API 서비스' },
  prod_his: { title: 'Production History', description: '생산 이력 조회 API 서비스' },
  defect_his: { title: 'Defect History', description: '불량 이력 조회 API 서비스' },
  alarm_his: { title: 'Alarm History', description: '알람 이력 조회 API 서비스' },
  maint_his: { title: 'Maintenance History', description: '보전 이력 조회 API 서비스' },
  shift_map: { title: 'Shift Map', description: '근무 교대 매핑 조회 API 서비스' },
  kpi_sum: { title: 'KPI Summary', description: 'KPI 집계 데이터 조회 API 서비스' },
}
